[tool.poetry]
name = "py-image-uploader"
version = "0.1.1"
description = "Upload images via APIs"
authors = ["DeadNews <uhjnnn@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/DeadNews/py-image-uploader"
repository = "https://github.com/DeadNews/py-image-uploader"
keywords = ["cli", "image", "uploader"]
classifiers = ["Environment :: Console", "Operating System :: OS Independent"]

[tool.poetry.scripts]
py-image-uploader = "py_image_uploader.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
pillow = "^9.1.1"
pyperclip = "^1.8.2"
python-dotenv = "^0.20.0"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
bandit = "^1.7.4"
black = "^22.3.0"
flake8 = "^4.0.1"
flake8-bugbear = "^22.4.25"
flake8-comprehensions = "^3.10.0"
flake8-implicit-str-concat = "^0.3.0"
flake8-pytest-style = "^1.6.0"
flake8-simplify = "^0.19.2"
isort = "^5.10.1"
mypy = "^0.961"
pep8-naming = "^0.13.0"
pre-commit = "^2.19.0"
pytest = "^7.1.2"
safety = "^1.10.3"
types-requests = "^2.27.30"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
line_length = 88
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = [
    "B404", # Importing subprocess
    "B603", # Calling subprocess.Popen without shell=True
    "B608", # Hardcoded sql expressions
]

[tool.pytest.ini_options]
addopts = "--verbose"
testpaths = ["tests"]
