on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true

jobs:
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: poetry

      - name: Install dependencies
        run: |
          poetry env use ${{ inputs.python-version }}
          poetry install

      - name: Check code quality
        run: poetry run poe ci
