on:
  workflow_call:
  # Permissions inherited from caller workflow

env:
  PYTHON_VERSION: "3.10"

jobs:
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ secrets.PYTHON_VERSION }}
          cache: poetry

      - name: Install dependencies
        run: |
          poetry env use ${{ secrets.PYTHON_VERSION }}
          poetry install

      - name: Check code quality
        run: poetry run poe ci
